// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1, arg2) {
  return window['go']['app']['App']['AddHost'](arg1, arg2);
}

export function AddNetwork(arg1) {
  return window['go']['app']['App']['AddNetwork'](arg1);
}

export function AddNetworkHost(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddNetworkHost'](arg1, arg2, arg3);
}

export function CreateMenu() {
  return window['go']['app']['App']['CreateMenu']();
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeleteNetwork(arg1) {
  return window['go']['app']['App']['DeleteNetwork'](arg1);
}

export function DeleteNetworkHost(arg1) {
  return window['go']['app']['App']['DeleteNetworkHost'](arg1);
}

export function ExportNetworkHosts(arg1) {
  return window['go']['app']['App']['ExportNetworkHosts'](arg1);
}

export function ImportNetworkHosts(arg1, arg2) {
  return window['go']['app']['App']['ImportNetworkHosts'](arg1, arg2);
}

export function ListHosts(arg1) {
  return window['go']['app']['App']['ListHosts'](arg1);
}

export function ListNetworkHosts(arg1, arg2) {
  return window['go']['app']['App']['ListNetworkHosts'](arg1, arg2);
}

export function ListNetworks(arg1) {
  return window['go']['app']['App']['ListNetworks'](arg1);
}

export function ListVPNServices() {
  return window['go']['app']['App']['ListVPNServices']();
}

export function ResetNetworkHostSetup(arg1) {
  return window['go']['app']['App']['ResetNetworkHostSetup'](arg1);
}

export function SaveFileWithDialog(arg1, arg2) {
  return window['go']['app']['App']['SaveFileWithDialog'](arg1, arg2);
}

export function SyncNetworkHostSetup(arg1) {
  return window['go']['app']['App']['SyncNetworkHostSetup'](arg1);
}
