// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {menu} from '../models';

export function AddHost(arg1:string,arg2:string):Promise<entity.Host>;

export function AddNetwork(arg1:string):Promise<entity.Network>;

export function AddNetworkHost(arg1:number,arg2:string,arg3:string):Promise<entity.NetworkHost>;

export function CreateMenu():Promise<menu.Menu>;

export function DeleteHost(arg1:number):Promise<void>;

export function DeleteNetwork(arg1:number):Promise<void>;

export function DeleteNetworkHost(arg1:number):Promise<void>;

export function ExportNetworkHosts(arg1:number):Promise<string>;

export function ImportNetworkHosts(arg1:number,arg2:string):Promise<void>;

export function ListHosts(arg1:string):Promise<Array<entity.Host>>;

export function ListNetworkHosts(arg1:number,arg2:string):Promise<Array<entity.NetworkHost>>;

export function ListNetworks(arg1:string):Promise<Array<entity.NetworkWithStatus>>;

export function ListVPNServices():Promise<Array<entity.VPNService>>;

export function ResetNetworkHostSetup(arg1:number):Promise<void>;

export function SaveFileWithDialog(arg1:string,arg2:string):Promise<string>;

export function SyncNetworkHostSetup(arg1:number):Promise<void>;
