name: Update Homebrew Cask

on:
  release:
    types: [published]

jobs:
  update-cask:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install Task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Get release info
        id: release
        run: |
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "download_url=${{ github.event.release.assets[0].browser_download_url }}" >> $GITHUB_OUTPUT

      - name: Download and get SHA256
        id: sha
        run: |
          # Find the ARM64 ZIP file from release assets
          ASSET_URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
                     jq -r '.assets[] | select(.name | contains("macos-arm64.zip")) | .browser_download_url')
          
          # Download the file temporarily to calculate SHA256
          curl -L -o temp.zip "$ASSET_URL"
          SHA256=$(shasum -a 256 temp.zip | cut -d' ' -f1)
          rm temp.zip
          
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "download_url=$ASSET_URL" >> $GITHUB_OUTPUT

      - name: Checkout homebrew tap
        uses: actions/checkout@v4
        with:
          repository: dmitryorlov/homebrew-splitr
          path: homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update Cask formula with Taskfile
        env:
          TAG: ${{ steps.release.outputs.tag_name }}
          SHA256: ${{ steps.sha.outputs.sha256 }}
          DOWNLOAD_URL: ${{ steps.sha.outputs.download_url }}
        run: |
          cd homebrew-tap
          
          # Use Taskfile to generate Cask formula
          task -d .. ci:update-cask

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Casks/splitr.rb
          git commit -m "Update Splitr to ${{ steps.release.outputs.tag_name }}"
          git push
